updates default build script to not reconfigure

diff --git a/scripts/osimperf-default-install-opensim b/scripts/osimperf-default-install-opensim
--- a/scripts/osimperf-default-install-opensim
+++ b/scripts/osimperf-default-install-opensim
@@ -37,8 +37,8 @@ OPENSIM_INSTALL_UNIX_FHS=${OPENSIM_INSTALL_UNIX_FHS:="ON"}
 OSPC_NUM_JOBS=${OSPC_NUM_JOBS:="4"}
 OSPC_OPENSIM_RUN_TESTS=${OSPC_OPENSIM_RUN_TESTS:="OFF"}
 
-OPENSIM_WITH_CASADI=${OPENSIM_WITH_MOCO:="OFF"}
-OPENSIM_WITH_TROPTER=${OPENSIM_WITH_MOCO:="OFF"}
+OPENSIM_WITH_CASADI=${OPENSIM_WITH_MOCO:="ON"}
+OPENSIM_WITH_TROPTER=${OPENSIM_WITH_MOCO:="ON"}
 
 echo "Installer directories:"
 echo "    OSPC_OPENSIM_SRC=$OSPC_OPENSIM_SRC"
@@ -54,28 +54,67 @@ mkdir -p $OSPC_OPENSIM_SRC
 mkdir -p $INSTALL_DIR
 mkdir -p $OSPC_BUILD_DIR
 
+OPENSIM_BUILD_DIR="$OSPC_BUILD_DIR/opensim-core"
+
 echo
 echo "Start installing dependencies."
 echo
 
-DEPENDENCIES_BUILD_DIR="$OSPC_BUILD_DIR/dependencies"
+ShouldReconfigureCmake() {
+	BUILD_DIR="$1"; shift
+
+	# Check global variable.
+	RECONFIGURE=${OSPC_CLEAN:="OFF"}
+
+	# If build dir does not exist, we should.
+	if [ -d $BUILD_DIR ]; then
+		RECONFIGURE="ON"
+	fi
+
+	# Try running cmake --build, if fails, try to reconfigure.
+	if [ $RECONFIGURE == "OFF" ]; then
+		if cmake --build $BUILD_DIR "-j$OSPC_NUM_JOBS" "$@" ; then
+			RECONFIGURE="OFF"
+		else
+			RECONFIGURE="ON"
+		fi
+	fi
+	echo $RECONFIGURE
+}
+
 DEPENDENCIES_INSTALL_DIR="$INSTALL_DIR/opensim-core-dependencies-install"
-OPENSIM_BUILD_DIR="$OSPC_BUILD_DIR/opensim-core"
 
-cmake \
-	-B "$DEPENDENCIES_BUILD_DIR" \
-	-S "$OSPC_OPENSIM_SRC/dependencies" \
-	-DCMAKE_INSTALL_PREFIX=$DEPENDENCIES_INSTALL_DIR \
-	-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE\
-	-DOPENSIM_WITH_CASADI=$OPENSIM_WITH_CASADI\
-	-DOPENSIM_WITH_TROPTER=$OPENSIM_WITH_TROPTER
-	# -DSUPERBUILD_ezc3d=on \
+# TODO HOTFIX!
 
-# Print dependencies cmake config.
-cmake "$DEPENDENCIES_BUILD_DIR" -LAH
+export OSPC_OPENSIM_DEPENDENCIES_INSTALL_DIR="/home/pep/opensim/osimperf/opensim-main-install/opensim-core-dependencies-install"
+if [ -v OSPC_OPENSIM_DEPENDENCIES_INSTALL_DIR ]; then
+	rsync -av $OSPC_OPENSIM_DEPENDENCIES_INSTALL_DIR/ $DEPENDENCIES_INSTALL_DIR
+else
+	exit 1
 
-# Build dependencies.
-cmake --build $DEPENDENCIES_BUILD_DIR "-j$OSPC_NUM_JOBS"
+	DEPENDENCIES_BUILD_DIR="$OSPC_BUILD_DIR/dependencies"
+
+	if [ $(ShouldReconfigureCmake() $DEPENDENCIES_BUILD_DIR) == "ON" ]; then
+
+		cmake \
+			-B "$DEPENDENCIES_BUILD_DIR" \
+			-S "$OSPC_OPENSIM_SRC/dependencies" \
+			-DCMAKE_INSTALL_PREFIX=$DEPENDENCIES_INSTALL_DIR \
+			-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE\
+			-DOPENSIM_WITH_CASADI=$OPENSIM_WITH_CASADI\
+			-DOPENSIM_WITH_TROPTER=$OPENSIM_WITH_TROPTER
+			# -DSUPERBUILD_ezc3d=on \
+		
+		# Print dependencies cmake config.
+		cmake "$DEPENDENCIES_BUILD_DIR" -LAH
+		
+		# Build dependencies.
+		cmake --build $DEPENDENCIES_BUILD_DIR "-j$OSPC_NUM_JOBS"
+
+	else
+		cmake "$DEPENDENCIES_BUILD_DIR" -LAH
+	fi
+fi
 
 echo "Completed installing dependencies."
 
@@ -83,34 +122,43 @@ echo
 echo "Start installing opensim-core."
 echo
 
-cmake \
-	-G "Unix Makefiles" \
-	-B "$OPENSIM_BUILD_DIR" \
-	-S $OSPC_OPENSIM_SRC \
-	-DBUILD_API_EXAMPLES=$BUILD_API_EXAMPLES \
-	-DBUILD_API_ONLY=$BUILD_API_ONLY \
-	-DBUILD_JAVA_WRAPPING=$BUILD_JAVA_WRAPPING \
-	-DBUILD_PYTHON_WRAPPING=$BUILD_PYTHON_WRAPPING \
-	-DBUILD_TESTING="$OSPC_OPENSIM_RUN_TESTS" \
-	-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
-	-DCMAKE_EXPORT_COMPILE_COMMANDS="ON" \
-	-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
-	-DCMAKE_VERBOSE_MAKEFILE=$CMAKE_VERBOSE_MAKEFILE \
-	-DOPENSIM_BUILD_INDIVIDUAL_APPS=$OPENSIM_BUILD_INDIVIDUAL_APPS \
-	-DOPENSIM_DEPENDENCIES_DIR=$DEPENDENCIES_INSTALL_DIR \
-	-DOPENSIM_DOXYGEN_USE_MATHJAX=$OPENSIM_DOXYGEN_USE_MATHJAX \
-	-DOPENSIM_INSTALL_UNIX_FHS=$OPENSIM_INSTALL_UNIX_FHS
-	# -DBUILD_JAVA_WRAPPING=on \
-	# -DBUILD_PYTHON_WRAPPING=on \
-	# -DOPENSIM_C3D_PARSER=ezc3d \
-	# -DSWIG_DIR=~/swig/share/swig \
-	# -DSWIG_EXECUTABLE=~/swig/bin/swig
+if [ $(ShouldReconfigureCmake() $OPENSIM_BUILD_DIR --target "install") == "ON" ]; then
+	cmake \
+		-G "Unix Makefiles" \
+		-B "$OPENSIM_BUILD_DIR" \
+		-S $OSPC_OPENSIM_SRC \
+		-DBUILD_API_EXAMPLES=$BUILD_API_EXAMPLES \
+		-DBUILD_API_ONLY=$BUILD_API_ONLY \
+		-DBUILD_JAVA_WRAPPING=$BUILD_JAVA_WRAPPING \
+		-DBUILD_PYTHON_WRAPPING=$BUILD_PYTHON_WRAPPING \
+		-DBUILD_TESTING="ON" \
+		-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
+		-DCMAKE_EXPORT_COMPILE_COMMANDS="ON" \
+		-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
+		-DCMAKE_VERBOSE_MAKEFILE=$CMAKE_VERBOSE_MAKEFILE \
+		-DOPENSIM_BUILD_INDIVIDUAL_APPS=$OPENSIM_BUILD_INDIVIDUAL_APPS \
+		-DOPENSIM_DEPENDENCIES_DIR=$DEPENDENCIES_INSTALL_DIR \
+		-DOPENSIM_DOXYGEN_USE_MATHJAX=$OPENSIM_DOXYGEN_USE_MATHJAX \
+		-DOPENSIM_INSTALL_UNIX_FHS=$OPENSIM_INSTALL_UNIX_FHS
+		# -DBUILD_JAVA_WRAPPING=on \
+		# -DBUILD_PYTHON_WRAPPING=on \
+		# -DOPENSIM_C3D_PARSER=ezc3d \
+		# -DSWIG_DIR=~/swig/share/swig \
+		# -DSWIG_EXECUTABLE=~/swig/bin/swig
 
-# Note: If you also provide PREFIX_PATH it messes up the paths to the dependencies, and cannot find ipopt anymore.
-# So do not set: -DCMAKE_PREFIX_PATH=$DEPENDENCIES_INSTALL_DIR
-
-# Print opensim-core cmake config.
-cmake "$OPENSIM_BUILD_DIR" -LAH
+	# Note: If you also provide PREFIX_PATH it messes up the paths to the dependencies, and cannot find ipopt anymore.
+	# So do not set: -DCMAKE_PREFIX_PATH=$DEPENDENCIES_INSTALL_DIR
+	
+	# Print opensim-core cmake config.
+	cmake "$OPENSIM_BUILD_DIR" -LAH
+	
+	cmake \
+		--build $OPENSIM_BUILD_DIR \
+		--target "install" \
+		"-j$OSPC_NUM_JOBS"
+else
+	cmake "$OPENSIM_BUILD_DIR" -LAH
+fi
 
 # Create symlink to compile_commands.json for IDE.
 ln_from="$OPENSIM_BUILD_DIR/compile_commands.json"
@@ -119,11 +167,6 @@ if [ "$ln_from" != "$ln_to" ]; then
 	ln -sf $ln_from $ln_to
 	echo "Created symlink: from $ln_from to $ln_to"
 fi
-
-cmake \
-	--build $OPENSIM_BUILD_DIR \
-	--target "install" \
-	"-j$OSPC_NUM_JOBS"
 
 echo "Completed installing opensim-core."
 
